// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api"
	mock "github.com/stretchr/testify/mock"
)

// ErrUpd is an autogenerated mock type for the ErrUpd type
type ErrUpd struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1, _a2
func (_m *ErrUpd) Execute(_a0 string, _a1 tgbotapi.Update, _a2 error) {
	_m.Called(_a0, _a1, _a2)
}

type mockConstructorTestingTNewErrUpd interface {
	mock.TestingT
	Cleanup(func())
}

// NewErrUpd creates a new instance of ErrUpd. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewErrUpd(t mockConstructorTestingTNewErrUpd) *ErrUpd {
	mock := &ErrUpd{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
