// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	metrics "github.com/egnd/go-toolbox/metrics"
	mock "github.com/stretchr/testify/mock"
)

// Counter is an autogenerated mock type for the Counter type
type Counter struct {
	mock.Mock
}

// Set provides a mock function with given fields: _a0
func (_m *Counter) Set(_a0 float64) {
	_m.Called(_a0)
}

// With provides a mock function with given fields: _a0
func (_m *Counter) With(_a0 ...string) metrics.Counter {
	_va := make([]interface{}, len(_a0))
	for _i := range _a0 {
		_va[_i] = _a0[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 metrics.Counter
	if rf, ok := ret.Get(0).(func(...string) metrics.Counter); ok {
		r0 = rf(_a0...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metrics.Counter)
		}
	}

	return r0
}

type mockConstructorTestingTNewCounter interface {
	mock.TestingT
	Cleanup(func())
}

// NewCounter creates a new instance of Counter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCounter(t mockConstructorTestingTNewCounter) *Counter {
	mock := &Counter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
