// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	metrics "github.com/egnd/go-toolbox/metrics"
	mock "github.com/stretchr/testify/mock"
)

// Histo is an autogenerated mock type for the Histo type
type Histo struct {
	mock.Mock
}

// Update provides a mock function with given fields: _a0
func (_m *Histo) Update(_a0 float64) {
	_m.Called(_a0)
}

// With provides a mock function with given fields: _a0
func (_m *Histo) With(_a0 ...string) metrics.Histo {
	_va := make([]interface{}, len(_a0))
	for _i := range _a0 {
		_va[_i] = _a0[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 metrics.Histo
	if rf, ok := ret.Get(0).(func(...string) metrics.Histo); ok {
		r0 = rf(_a0...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metrics.Histo)
		}
	}

	return r0
}

type mockConstructorTestingTNewHisto interface {
	mock.TestingT
	Cleanup(func())
}

// NewHisto creates a new instance of Histo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHisto(t mockConstructorTestingTNewHisto) *Histo {
	mock := &Histo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
