// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Histo is an autogenerated mock type for the Histo type
type Histo struct {
	mock.Mock
}

// Update provides a mock function with given fields: _a0
func (_m *Histo) Update(_a0 float64) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewHisto interface {
	mock.TestingT
	Cleanup(func())
}

// NewHisto creates a new instance of Histo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHisto(t mockConstructorTestingTNewHisto) *Histo {
	mock := &Histo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
