// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Increment is an autogenerated mock type for the Increment type
type Increment struct {
	mock.Mock
}

// Add provides a mock function with given fields: _a0
func (_m *Increment) Add(_a0 float64) {
	_m.Called(_a0)
}

// Inc provides a mock function with given fields:
func (_m *Increment) Inc() {
	_m.Called()
}

type mockConstructorTestingTNewIncrement interface {
	mock.TestingT
	Cleanup(func())
}

// NewIncrement creates a new instance of Increment. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIncrement(t mockConstructorTestingTNewIncrement) *Increment {
	mock := &Increment{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
