// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	metrics "github.com/egnd/go-toolbox/metrics"
	mock "github.com/stretchr/testify/mock"
)

// IncrementBuilder is an autogenerated mock type for the IncrementBuilder type
type IncrementBuilder struct {
	mock.Mock
}

// Build provides a mock function with given fields:
func (_m *IncrementBuilder) Build() metrics.Increment {
	ret := _m.Called()

	var r0 metrics.Increment
	if rf, ok := ret.Get(0).(func() metrics.Increment); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metrics.Increment)
		}
	}

	return r0
}

// With provides a mock function with given fields: _a0
func (_m *IncrementBuilder) With(_a0 ...string) metrics.IncrementBuilder {
	_va := make([]interface{}, len(_a0))
	for _i := range _a0 {
		_va[_i] = _a0[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 metrics.IncrementBuilder
	if rf, ok := ret.Get(0).(func(...string) metrics.IncrementBuilder); ok {
		r0 = rf(_a0...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metrics.IncrementBuilder)
		}
	}

	return r0
}

type mockConstructorTestingTNewIncrementBuilder interface {
	mock.TestingT
	Cleanup(func())
}

// NewIncrementBuilder creates a new instance of IncrementBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIncrementBuilder(t mockConstructorTestingTNewIncrementBuilder) *IncrementBuilder {
	mock := &IncrementBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
