// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	metrics "github.com/egnd/go-toolbox/metrics"
	mock "github.com/stretchr/testify/mock"
)

// Increment is an autogenerated mock type for the Increment type
type Increment struct {
	mock.Mock
}

// Inc provides a mock function with given fields:
func (_m *Increment) Inc() {
	_m.Called()
}

// With provides a mock function with given fields: _a0
func (_m *Increment) With(_a0 ...string) metrics.Increment {
	_va := make([]interface{}, len(_a0))
	for _i := range _a0 {
		_va[_i] = _a0[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 metrics.Increment
	if rf, ok := ret.Get(0).(func(...string) metrics.Increment); ok {
		r0 = rf(_a0...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metrics.Increment)
		}
	}

	return r0
}

type mockConstructorTestingTNewIncrement interface {
	mock.TestingT
	Cleanup(func())
}

// NewIncrement creates a new instance of Increment. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIncrement(t mockConstructorTestingTNewIncrement) *Increment {
	mock := &Increment{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
