name: Pipeline
on: 
  push: 
    branches:
     - '*'
jobs:

  todos:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - run: make check-todos
  conflicts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make check-conflicts
  gitflow:
    runs-on: ubuntu-latest
    if: "!contains(github.ref, 'master')"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: make check-master

  lint:
    runs-on: ubuntu-latest
    needs: [todos, conflicts]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.20
    - run: wget https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh -O - | sudo sh -s -- -b $(go env GOPATH)/bin v1.52.0
    - run: make lint
  
  units:
    runs-on: ubuntu-latest
    needs: [todos, conflicts]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.20
    - run: make coverage COVER_REPORT=false
    - run: cp .profiles/cover.out coverage.txt
    - uses: codecov/codecov-action@v3
