name: Pipeline
on: 
  push: 
    branches:
     - '*'
jobs:

  todos:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - run: make check-todos
  conflicts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make check-conflicts
  gitflow:
    runs-on: ubuntu-latest
    if: "!contains(github.ref, 'master')"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: make check-master

  lint:
    runs-on: ubuntu-latest
    needs: [todos, conflicts]
    steps:
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1
  
  units:
    runs-on: ubuntu-latest
    needs: [todos, conflicts]
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - uses: actions/checkout@v3
      - run: make coverage DISABLE_HTML=true
      - run: cp .profiles/cover.out coverage.txt
      - uses: codecov/codecov-action@v3
